export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const RETRIEVE_INGREDIENTS_FAIL = 'RETRIEVE_INGREDIENTS_FAIL'

export const FOOD_PURCHASE_START = 'FOOD_PURCHASE_START'
export const FOOD_PURCHASE_SUCCESS = 'FOOD_PURCHASE_SUCCESS'
export const FOOD_PURCHASE_FAIL = 'FOOD_PURCHASE_FAIL'
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'