export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const RETRIEVE_INGREDIENTS_FAIL = 'RETRIEVE_INGREDIENTS_FAIL'

export const FOOD_PURCHASE_SUCCESS = 'FOOD_PURCHASE_SUCCESS'
export const FOOD_PURCHASE_FAIL = 'FOOD_PURCHASE_FAIL'